question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
     "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The Eiffel Tower is taller than the Statue of Liberty.", "answer": "True"},
    {"text": "A group of crows is called a 'murder'.", "answer": "True"},
    {"text": "Coca-Cola was originally green in color.", "answer": "False"},
    {"text": "Polar bears are left-handed.", "answer": "False"},
    {"text": "Goldfish have a three-second memory.", "answer": "False"},
    {"text": "The human brain stops growing after the age of 18.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "The capital of Canada is Toronto.", "answer": "False"},
    {"text": "The Earth has two moons.", "answer": "False"},
    {"text": "Ostriches can fly.", "answer": "False"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "True"},
    {"text": "Penguins are mammals.", "answer": "False"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "The star sign 'Leo' is represented by a crab.", "answer": "False"},
    {"text": "Albert Einstein failed math in school.", "answer": "False"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "The Sahara Desert is the largest desert in the world.", "answer": "False"},
    {"text": "The Mona Lisa was painted by Michelangelo.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The tallest mountain in the world is Mount Everest.", "answer": "True"},
    {"text": "The currency used in Japan is the Yuan.", "answer": "False"}
]
